name: Carpenter
on:
  push:
    branches:
      - "**"
  release:
    types:
      - published
jobs:
  carpenter:
    uses: jdowni000/arcaflow-reusable-workflows/.github/workflows/carpenter.yaml@create
